CREATE TABLE orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_number VARCHAR(191) UNIQUE NOT NULL,
    order_status TINYINT NOT NULL,
    payment_status TINYINT NOT NULL,
    logistics_status TINYINT NOT NULL,
    payment_id BIGINT UNSIGNED,
    payment_provider VARCHAR(191) NOT NULL,
    payment_method VARCHAR(191) NOT NULL,
    logistics_id BIGINT UNSIGNED,
    logistics_provider VARCHAR(191) NOT NULL,
    logistics_method VARCHAR(191) NOT NULL,
    logistics_cvs_code VARCHAR(191),
    fee_cost INT NOT NULL,
    shipping_cost INT NOT NULL,
    total_price INT NOT NULL,
    customer_name VARCHAR(191) NOT NULL,
    customer_email VARCHAR(191) NOT NULL,
    customer_phone VARCHAR(191) NOT NULL,
    customer_address VARCHAR(191) NOT NULL,
    payment_time TIMESTAMP,
    cvs_info TEXT,
    payment_log TEXT,
    logistics_log TEXT,
    logistics_tracking_number VARCHAR(191),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    FOREIGN KEY(payment_id) REFERENCES payments(id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY(logistics_id) REFERENCES logistics(id) ON UPDATE CASCADE ON DELETE SET NULL
);
